### ISSUE TITLE
Directory issue with fig in boot2docker

### ISSUE THREAD

**Issue by mikehaertl** [dduportal/dockerfiles#5]
Sorry if this is a crosspost but I'm not really sure, where's the best place to report this issue. I have already added comment here: https://github.com/docker/fig/issues/598#issuecomment-75119084

I have a dockerized [Yii2 PHP app template](https://github.com/codemix/yii2-dockerized), that works fine with docker and fig under Linux and Mac OS X. Now I've tried to run this app on a Windows 8.1 box with boot2docker. So I've created an alias for `fig` inside the boot2docker VM as recommended in the issue referenced above. 

When I now try to fire up the docker container i get this error:

```
web_1 | AH00526: Syntax error on line 38 of /etc/apache2/apache2.conf:
web_1 | DocumentRoot must be a directory
yii2_web_1 exited with code 1
```

Even though, the directory definitely exists. The strange part is, that I can run the image that was built by fig manually:

```
docker run -p 80:80 yii2_web
```

This works. Now I wonder, what `fig` does different. Is there a way to debug fig, e.g. to output the explicit `docker` command that was issued by fig?

Or any other idea what could cause this issue?

**Comment by mikehaertl** [comment]
Moved this over to fig: https://github.com/docker/fig/issues/994.

If you still have an idea, please don't hesitate to answer here, as I'm really stuck here.

**Comment by mikehaertl** [comment]
Found it out. It's very important, that absolute paths are used for shared volumes from the host:

```
web:
    build: ./
    ports:
        - "8080:80"
    expose:
        - "80"
    volumes:
        - /c/Users/Mike/Documents/yii2:/var/www/html/
```

**Comment by dduportal** [comment]
Thanks @mikehaertl for pointing this out, this seems to be a big struggle on fig...

**Comment by lbesson** [comment]
a (bad?) solution in order to use relative paths could be to use following alias
`alias docker-compose="docker run -v  \"\$(pwd)\":\"\$(pwd)\" -v /var/run/docker.sock:/var/run/docker.sock -w \"\$(pwd)\"  -ti dduportal/docker-compose:latest"`

**Comment by ksylvan** [comment]
@lbesson That is brilliant! Now my docker-compose command is this:

    #!/bin/sh
    docker run --rm -v $(pwd):/app \
       -v /var/run/docker.sock:/var/run/docker.sock \
       -v "$(pwd):$(pwd)" -w "$(pwd)" \
       -it dduportal/docker-compose:latest ${1+"$@"}

And now it works the same as the native docker-compose command. Thanks.
