### ISSUE TITLE
[Proposal] Multiple tags for compose & readme

### ISSUE THREAD

**Issue by josephpage** [dduportal/dockerfiles#8]
Hey Damien !

Can you provide multiple tags for docker-compose ? probably based on git tags
Now, when a new docker-compose version is released, previous releases disappear from Docker Hub, making difficult for us to test a backward compatibility.

Also, you should link the description in registry with a readme file, which allows the community to contribute to docs.

Thanks again.

**Comment by josephpage** [comment]
I didn't see that you had transfered this Dockerfile to dduportal-dockerfiles/docker-compose
Sorry.

**Comment by dduportal** [comment]
No problem :) Thanks for proposal anyway !
